server:
  port: ${PORT}

spring:
  flyway:
    schema: public
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${SQL_URL}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  file:
    name: project.log
