server:
    port: ${APPLICATION_PORT}

sender:
    email: ${EMAIL}
    link: ${LINK}

security:
    secret: e9fe2e88cd731b2f102e90439103eabf69dadf4d40f0436c9042d229bb85f7e4
    access-token:
        token-name: ${ACCESS_TOKEN_NAME}
        expiration: 3600000
    refresh-token:
        expiration: 86400000

spring:
    flyway:
        schema: public
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    mail:
        host: smtp.gmail.com
        post: 587
        username: ${EMAIL}
        password: ${APP_PASSWORD}
        properties:
            mail:
                smtp:
                    ssl:
                        trust: "*"
                    auth: true
                    starttls:
                        enable: true

logging:
    file:
        name: project.log

springdoc:
    swagger-ui:
        path=/swagger-ui