server:
  port: ${PORT}

sender:
  email: ${EMAIL}
  link: ${LINK}

security:
  secret: ${SECRET}
  access-token:
    token-name: ${ACCESS_TOKEN_NAME}
    expiration: ${ACCESS_TIME}
  refresh-token:
    expiration: ${REFRESH_TIME}

spring:
  flyway:
    schema: public
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:${SQL_PORT}/${DB_NAME}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  redis:
    host: ${REDIS_HOSTNAME}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    timeout: ${REDIS_SAVE}
  mail:
    host: smtp.gmail.com
    post: 587
    username: ${EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true

logging:
  file:
    name: project.log
